remove_devices:
  name: Remove devices
  description: Remove devices.
  target:
    entity:
      integration: miwifi
      domain: device_tracker

clear_store:
  name: Clear devices store
  description: Clear devices store.