calc_passwd:
  name: Calculate passwd
  description: Calculate default passwd.
  fields:
    ip_address:
      name: IP address
      description: IP address of the router.
      required: true
      example: "192.168.31.1"
      selector:
        text:

request:
  name: Send request
  description: Send request to router.
  fields:
    ip_address:
      name: IP address
      description: IP address of the router.
      required: true
      example: "192.168.31.1"
      selector:
        text:
    uri:
      name: Uri
      description: Request uri.
      required: true
      example: "misystem/led"
      selector:
        text:
    body:
      name: Body
      description: Request body.
      required: false
      example: |
        on: 1
      selector:
        object: