name: Checks

on:
  push:
  pull_request:
  schedule:
    - cron: '22 20 * * 6'

jobs:
  py-lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "custom_components/miwifi"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: true
          use-mypy: true
          use-isort: false
          extra-pylint-options: "--disable=duplicate-code --disable=too-many-instance-attributes"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: "--show-error-codes --show-error-context --ignore-missing-imports --pretty --show-error-codes"
          extra-isort-options: ""

  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1

  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"

  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "hacs/action@main"
        with:
          category: "integration"

