name: HASS and HACS

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
      - uses: "hacs/action@main"
        with:
          category: "integration"